# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 00:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetyuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 16, 0, 23, 24, 319211, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweetyuser',
            name='first_name',
            field=models.CharField(default='janusz', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweetyuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tweetyuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tweetyuser',
            name='last_name',
            field=models.CharField(default='janusz', max_length=50),
            preserve_default=False,
        ),
    ]
