# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweety', '0005_auto_20160116_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
