# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweety', '0008_auto_20160116_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetyuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tweetyuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
